# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: OctoInstaller@5
  inputs:
    version: '*'

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: MSBuild@1
  inputs:
    solution: '**/*.sln'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArguments: '/t:Build /p:RunOctoPack=true /p:OctoPackPackageVersion=$(Build.BuildNumber) /p:OctoPackEnforceAddingFiles=true'

- task: Bash@3
  displayName: Generate ReleaseNotes
  inputs:
    targetType: inline
    script: |
      git log -1 > ReleaseNotes.txt
- task: OctopusPush@5
  inputs:
    OctoConnectedServiceName: 'octopus'
    Space: 'Spaces-1'
    Package: '$(System.TeamProject)\obj\octopacked\$(System.TeamProject).$(Build.BuildNumber).nupkg'
    Replace: 'false'
    
- task: OctopusCreateRelease@5
  inputs:
    OctoConnectedServiceName: 'octopus'
    Space: 'Spaces-1'
    ProjectGroup: 'Web'
    ProjectName: '$(System.TeamProject)'
    ReleaseNumber: '$(Build.BuildNumber)'
    Channel: 'develop'
    AdditionalArguments: '--releaseNoteFile=ReleaseNotes.txt'