# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    
- task: Bash@3
  displayName: Generate ReleaseNotes
  inputs:
    targetType: inline
    script: |
      git log -1 > ReleaseNotes.txt

- task: OctopusPack@4
  displayName: Prepare Octopus Package
  inputs:
    PackageId: $(Build.Repository.Name)
    PackageFormat: 'Zip'
    PackageVersion: $(Build.BuildNumber)

- task: OctopusPush@4
  displayName: Upload Octopus Package
  inputs:
    OctoConnectedServiceName: 'octopus'
    Space: 'Spaces-1'
    Package: k8s-$(imageName).$(Build.BuildNumber)-gke.zip
    Replace: 'false'

- task: OctopusCreateRelease@4
  displayName: Create Octopus Release
  inputs:
    OctoConnectedServiceName: 'octopus'
    Space: 'Spaces-1'
    ProjectGroup: 'Web'
    ProjectName: $(Build.Repository.Name)
    ReleaseNumber: $(Build.BuildNumber)
    channel: $(Build.SourceBranchName)
    AdditionalArguments: '--releaseNoteFile=ReleaseNotes.txt'
